- hosts: localhost
  name: Initial Deploy
  tasks:
  - name: Get Session Confirmation
    # we need a valid session conf before we can do anything else
    bcc_session_confirmation:
      action: get_session
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
    register: session_data
    
  - name: Login
    bcc_login:
      action: login
      cookie: "{{ session_data.session_cookie }}"
      # get login credentials from environment variables
      username: "{{ lookup('env','BCC_USER') }}"
      password: "{{ lookup('env','BCC_PASSWORD') }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}" 
      
  - name: Get Target By Name
    bcc_get_target_by_name:
      action: get_target
      cookie: "{{ session_data.session_cookie }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
      targetName: "Test"
    register: result
       
  - name: Initial Deploy
    bcc_initial_deployment:
      action: initial_deployment
      cookie: "{{ session_data.session_cookie }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
      targetID: "{{ result.target.targetDef.ID }}"
    register: deployresult
    
  - debug: var=deployresult
      


