- hosts: localhost
  name: Import Toplogy
  tasks:
  - name: Get Session Confirmation
    # we need a valid session conf before we can do anything else
    bcc_session_confirmation:
      action: get_session
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
    register: session_data
    
  - name: Login
    bcc_login:
      action: login
      cookie: "{{ session_data.session_cookie }}"
      # get login credentials from environment variables
      username: "{{ lookup('env','BCC_USER') }}"
      password: "{{ lookup('env','BCC_PASSWORD') }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}" 
          
  - name: Import Toplogy
    bcc_import_topology:
      action: import
      cookie: "{{ session_data.session_cookie }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
      # The following line is importing the base64 topology from a file
      base64XML: '{{ lookup(''template'', ''topologyImportData/base64Topology'', convert_data=False) }}'   
    register: result
    
  - debug: var=result
      


