- hosts: localhost
  name: Delete Agent
  tasks:
  - name: Get Session Confirmation
    # we need a valid session conf before we can do anything else
    bcc_session_confirmation:
      action: get_session
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
    register: session_data
    
  - name: Login
    bcc_login:
      action: login
      cookie: "{{ session_data.session_cookie }}"
      # get login credentials from environment variables
      username: "{{ lookup('env','BCC_USER') }}"
      password: "{{ lookup('env','BCC_PASSWORD') }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}" 
      
  - name: Get Agent ID
    bcc_get_agent_id:
      action: get_agent_id
      cookie: "{{ session_data.session_cookie }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
      # Lookup TestAgent1 that belongs to target CompleteTest
      targetName: "CompleteTest"
      agentName: "TestAgent1"
    # Save the result to agentresult
    register: agentresult
    
  - name: Delete Agent
    bcc_delete_agent:
      action: delete_agent
      cookie: "{{ session_data.session_cookie }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
      # use the data we got back from get_agent_id to pass the agent ID in
      agentID: "{{ agentresult.agentID.agentId }}"
      
    # This makes any changes we made live 
  - name: Initialize Toplogy
    bcc_initialize_topology:
      action: initialize
      cookie: "{{ session_data.session_cookie }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"      
