- hosts: localhost
  name: Full Deploy
  tasks:
  - name: Get Session Confirmation
    # we need a valid session conf before we can do anything else
    bcc_session_confirmation:
      action: get_session
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
    register: session_data
    
  - name: Login
    bcc_login:
      action: login
      cookie: "{{ session_data.session_cookie }}"
      # get login credentials from environment variables
      username: "{{ lookup('env','BCC_USER') }}"
      password: "{{ lookup('env','BCC_PASSWORD') }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}" 
      
  - name: Get Target By Name
    bcc_get_target_by_name:
      action: get_target
      cookie: "{{ session_data.session_cookie }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
      targetName: "CompleteTest"
    # Save the results of getting the target into targetresult variable
    register: targetresult
      
  - name: Full Deploy
    bcc_full_deploy:
      action: full_deploy
      cookie: "{{ session_data.session_cookie }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
      targetID: "{{ targetresult.target.targetDef.ID }}"
    register: deployresult
    
    # dump the results returned by full_deploy to stdout
  - debug: var=deployresult
      


