- hosts: localhost
  name: Get Agent ID
  tasks:
  - name: Get Session Confirmation
    # we need a valid session conf before we can do anything else
    bcc_session_confirmation:
      action: get_session
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
    register: session_data
    
  - name: Login
    bcc_login:
      action: login
      cookie: "{{ session_data.session_cookie }}"
      # get login credentials from environment variables
      username: "{{ lookup('env','BCC_USER') }}"
      password: "{{ lookup('env','BCC_PASSWORD') }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}" 
         
  - name: Get Agent by name
    bcc_get_agent_by_name:
      action: get_agent_by_name
      cookie: "{{ session_data.session_cookie }}"
      endpoint: "{{ lookup('env','BCC_ENDPOINT') }}"
      # Lookup TestAgent1 that belongs to target CompleteTest
      targetName: "CompleteTest"
      agentName: "TestAgent2"
    # Save the result to agentresult
    register: agentresult
    
    # dump the agentID to stdout
  - debug: var=agentresult.agent
      


