- gather_facts: true
  hosts: localhost
  name: Delete endeca1_instance
  tasks:
  - name: authenticate
    oc_authenticate:
      endpoint: '{{ endpoint }}'
      password: '{{ password }}'
      user: '{{ user }}'
    register: cookie
  - name: stop orchestration
    oc_orchestration:
      action: stop
      cookie: '{{ cookie.cookie }}'
      endpoint: '{{ endpoint }}'
      resourcename: '{{ resourcebase }}/{{ envorchestration }}'
    register: stopresult
  - delay: 30
    name: monitor orchestartion
    oc_orchestration:
      action: list
      cookie: '{{cookie.cookie}}'
      endpoint: '{{endpoint}}'
      resourcename: '{{resourcebase}}/{{ envorchestration }}'
    register: monitor
    retries: 20
    until: monitor.list.result[0].status == "stopped"
    when: ( stopresult.list.has_key("status") ) or ( stopresult.list.message.find("already stopped") == 1 )
  - name: delete orchestration
    oc_orchestration:
      action: delete
      cookie: '{{cookie.cookie}}'
      endpoint: '{{endpoint}}'
      resourcename: '{{resourcebase}}/{{ envorchestration }}'
  vars_files:
  - ../oraclecompute_vars.yaml
  - endeca1_instance_vars.yaml
