- gather_facts: true
  hosts: localhost
  name: Create atgdb_instance
  tasks:
  - name: authenticate
    oc_authenticate:
      endpoint: '{{ endpoint }}'
      password: '{{ password }}'
      user: '{{ user }}'
    register: cookie
  - name: add orchestration
    oc_orchestration:
      action: add
      cookie: '{{ cookie.cookie }}'
      endpoint: '{{ endpoint }}'
      orchestration: '{{ lookup(''template'', ''../templates/atgdb.json'', convert_data=False) }}'
      resourcename: '{{ resourcebase }}'
  - name: start orchestration
    oc_orchestration:
      action: start
      cookie: '{{ cookie.cookie }}'
      endpoint: '{{ endpoint }}'
      resourcename: '{{ resourcebase }}/{{ envorchestration }}'
  - delay: 60
    name: monitor orchestration
    oc_orchestration:
      action: list
      cookie: '{{cookie.cookie}}'
      endpoint: '{{endpoint}}'
      resourcename: '{{resourcebase}}/{{ envorchestration }}'
    register: monitor
    retries: 15
    until: monitor.list.result[0].status == "ready"
  vars_files:
  - ../oraclecompute_vars.yaml
  - atgdb_instance_vars.yaml
