- gather_facts: true
  hosts: localhost
  name: Delete dbcsTest_dbcs_instance
  tasks:
  - name: Delete dbcs instance
    oc_service:
      action: delete
      endpoint: '{{ dbcsendpoint }}'
      name: dbcsTest
      password: '{{ password }}'
      service: dbcs
      tenant: '{{ tenant }}'
      user: '{{ dbcsuser }}'
  vars_files:
  - ../oraclecompute_vars.yaml
